export const VARIABLES = {
  ACTIONS: {
    BLINK_RED_LED: "BLINK_RED_LED",
    BLINK_COLOR_ITERATION: "BLINK_COLOR_ITERATION",
    BLINK_GREEN_LED: "BLINK_GREEN_LED",
    BLINK_BLUE_LED: "BLINK_BLUE_LED",
  },
  COLOUR: {
    RED: "RED",
    GREEN: "GREEN",
    BLUE: "BLUE",
  },
};
